### ISSUE TITLE
Warped image when switching between Portrait and Landscape mode

### ISSUE THREAD

**Issue by markfguerra** [markfguerra/GLWallpaperService#10]
The image looks fine as it loads up the first time in Portrait mode. Switch the screen orientation to landscape and the image will be squished and off-center.

Issue is present in current master branch, commit 0a5e282c0f.

If anyone has any additional information, please post it here.

**Comment by markfguerra** [comment]
A contributor "mblaster" has sent in a patch to correct this issue. If you have time and want to help, please test that this patch works well on your device.

You can check out this branch to review the fix
https://github.com/markfguerra/GLWallpaperService/tree/archive/bug-reorient (Edit: Branch deleted. Linked to a tag)

**Comment by mblaster** [comment]
The same issue can be invoked by certain applications without switching between portrait and landscape, even after the patch.

On CM7 for example the camera app, when used in portrait mode (just open the app and press home) has the same effect. With the patch present it at least vanishes after the next screen off or orientation change. Still looks a bit messy when it occurs.

Had no time looking further into this yet.

**Comment by markfguerra** [comment]
I created an APK with this patch included. It would be helpful if anyone willing can please test on their device and post their results and device info here. If possible please compare vs the unpatched version.

Here's what I'm looking for:
1- Does it resolve the warped image after screen rotate issue? (it should)
2- Does it affect the WaitForCondition bug that causes the animation to freeze? IE does that problem occur more frequently, less frequently, or about the same?

Patched version:
http://files.markguerra.net/glwallpaperservice/issue10/GLWallpaperTest-bug-reorient-24c2325.apk

Unpatched version:
http://files.markguerra.net/glwallpaperservice/rel/GLWallpaperTest-rel-v0.9.apk

**Comment by dkeese** [comment]
I can confirm that this fixes the issue on my HTC Incredible, using LauncherPro. Froyo.

However, I have not encountered this issue in my own wallpapers yet. Probably because I recreate the viewport stuff in onSurfaceChanged().

On my Acer Iconia Tab, the cube does not appear at all in either of these versions--just pure green background. Does this test wallpaper use anything fancy, like huge textures or something that might not be supported on 100% of GLES implementations?

**Comment by markfguerra** [comment]
This issue is being closed because the project is being moved to the [GLWallpaperService GitHub organization](https://github.com/GLWallpaperService/GLWallpaperService)

If anyone is still having this problem, please go there and open new issue or pull request. Don't forget to link back to this page.
