### ISSUE TITLE
Textures show on emulator, not on phone

### ISSUE THREAD

**Issue by RenegadeMaster** [markfguerra/GLWallpaperService#17]
Hi,

Great work, by the way. I'm quite willing to contribute. 

I have a wallpaper that maps some textures onto simple squares and rotates them. Textures are loaded from .png images using BitmapFactory. On any emulator I try, it renders correctly. On my phone, the textures don't show up. It's very odd. I based my code on the Deep wallpaper example which also uses GLWallpaperService. His app seems to have the same problem.

Any ideas? I find it odd that it works on Froyo and Gingerbread AVD, but on phone... everything is fine except the textures. Thanks
Dirk

**Comment by markfguerra** [comment]
This issue is being closed because the project is being moved to the [GLWallpaperService GitHub organization](https://github.com/GLWallpaperService/GLWallpaperService)

If you're still having this problem, please go there and open new issue or pull request. Don't forget to link back to this page.
