### ISSUE TITLE
Tesxtures not Rendering

### ISSUE THREAD

**Issue by sourceBreaker** [markfguerra/GLWallpaperService#19]
Hi, 
I am using cocos2d Android https://github.com/ZhouWeikuan/cocos2d/
and i am using your GLSurfaceView.java for Live wallpaper and what i have done that i called my scene.draw() in onDrawframe()   i noticed that gl is drawing my textures(texture.draw is being called for each texture) but i cannot see any texture on screen.

**Comment by sourceBreaker** [comment]
Hi my Live wallpaper only working fro Nexus One and not working on any other device (e.g Nexus S , Motorolla Atrix , Glaxy tab) Is there any issue with open GL configuration ?

**Comment by markfguerra** [comment]
This issue is being closed because the project is being moved to the [GLWallpaperService GitHub organization](https://github.com/GLWallpaperService/GLWallpaperService)

If you're still having this problem, please go there and open new issue or pull request. Don't forget to link back to this page.
