### ISSUE TITLE
Encourage library reference over JAR

### ISSUE THREAD

**Issue by jayschwa** [markfguerra/GLWallpaperService#27]
The current documentation provides instructions on creating a JAR and then importing that JAR into another project. However, this is not the procedure recommended by the official Android developer documentation: https://developer.android.com/tools/projects/projects-eclipse.html#SettingUpLibraryProject

I switched MasDennis/Rajawali@4adf085 over to this method late last year and haven't really had any problems with the transition.

**Comment by markfguerra** [comment]
That's interesting, I didn't know that.

Would you mind opening this issue on the GLWallpaperService GitHub organization? That's the new place where we'll be working on issues and pull requests going forward.

https://github.com/GLWallpaperService/GLWallpaperService

**Comment by jayschwa** [comment]
GLWallpaperService/GLWallpaperService#2
