### ISSUE TITLE
ClassNotFoundException on WallpaperService at run time

### ISSUE THREAD

**Issue by wolfgangabersdorf** [markfguerra/GLWallpaperService#28]
"To view the wallpaper, use the Android Live Wallpaper picker screen, and select your Wallpaper"

is error on emulator and device: The application .... has stopped unexpectedly.Please try again.

Please help me.

logcat from Eclipse emulator:

03-12 10:12:15.662: E/AndroidRuntime(558): FATAL EXCEPTION: main
03-12 10:12:15.662: E/AndroidRuntime(558): java.lang.RuntimeException: Unable to instantiate service ru.my.glwalpapper.MyWallpaperService: java.lang.ClassNotFoundException: ru.my.glwalpapper.MyWallpaperService in loader dalvik.system.PathClassLoader[/data/app/ru.my.glwalpapper-1.apk]
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2943)
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.app.ActivityThread.access$3300(ActivityThread.java:125)
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2087)
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.os.Looper.loop(Looper.java:123)
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.app.ActivityThread.main(ActivityThread.java:4627)
03-12 10:12:15.662: E/AndroidRuntime(558):  at java.lang.reflect.Method.invokeNative(Native Method)
03-12 10:12:15.662: E/AndroidRuntime(558):  at java.lang.reflect.Method.invoke(Method.java:521)
03-12 10:12:15.662: E/AndroidRuntime(558):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
03-12 10:12:15.662: E/AndroidRuntime(558):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
03-12 10:12:15.662: E/AndroidRuntime(558):  at dalvik.system.NativeStart.main(Native Method)
03-12 10:12:15.662: E/AndroidRuntime(558): Caused by: java.lang.ClassNotFoundException: ru.my.glwalpapper.MyWallpaperService in loader dalvik.system.PathClassLoader[/data/app/ru.my.glwalpapper-1.apk]
03-12 10:12:15.662: E/AndroidRuntime(558):  at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
03-12 10:12:15.662: E/AndroidRuntime(558):  at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
03-12 10:12:15.662: E/AndroidRuntime(558):  at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
03-12 10:12:15.662: E/AndroidRuntime(558):  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2940)
03-12 10:12:15.662: E/AndroidRuntime(558):  ... 10 more

**Comment by mawo78** [comment]
Hi,
When creating a virtual machine, make sure to select the "GPU emulation" option from the hardware menu.
OpenGL is supported in Android Emulator since version 2.3.
Please also check if you have latest version of emulator.
http://android-developers.blogspot.fi/2012/04/faster-emulator-with-better-hardware.html
I hope it could help you,
Best Regards,
Marcin

**Comment by wolfgangabersdorf** [comment]
No. This error is persists.

**Comment by markfguerra** [comment]
I think this is an issue with the project setup. Your error message indicates that the class loader cannot find your MyWallpaperService class. 

Check out this link for a possible resolution: http://stackoverflow.com/questions/10074938/android-class-path-exception

More info
http://stackoverflow.com/questions/7185488/android-what-is-the-folder-name-of-the-jar-files-lib-or-libs
http://tools.android.com/recent/dealingwithdependenciesinandroidprojects

Does moving the Jar from the lib/ folder to the libs/ folder solve your issue?

Make sure your libs/ folder is on your classpath.

**Comment by wolfgangabersdorf** [comment]
Yes. ok.
thank you ever so much
