### ISSUE TITLE
Question: should this be used if I wish to show animated GIF or video file in live wallpaper?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [markfguerra/GLWallpaperService#33]
Or is it possible to do it with a normal one?
If it's possible only by using GLWallpaperService, may I ask how ?
I've searched in so many places, and I don't see a single place to show how to show video files content on live wallpaper.

**Comment by markfguerra** [comment]
Thanks for the question 👍the short answer is, no, this isn't the tool for the job in my opinion.

More detail at this link, let's continue the conversation there https://github.com/GLWallpaperService/GLWallpaperService/issues/14
