### ISSUE TITLE
Strange glitches on older device (G1)

### ISSUE THREAD

**Issue by mblaster** [markfguerra/GLWallpaperService#6]
I tried to run a LWP created from this class on my old G1 (Cynogenmod6 and Biffmod) and it behaved very strange:

1) after opening the LWP in the picker a black screen is rendered
2) open LWP settings, press back -> the wallpaper is rendered correctly now
3) set the LWP -> either the LWP crashes or it again renders a black screen
4) not always reproducable: if it did not crash, calling up the wallpaper picker, chosing the wallpaper and pressing home may lead to an apparently working LWP
5) it crashes on screen off

I will try another ROM on my G1 now to rule out that it was just a ROM issue (already checked 2). Will provide logcat later...

mblaster

€: No differnent behaviour on enomther's ROM

Here is a logcat for playing around with the settings dialogue:
http://pastebin.com/fbBCCLZb

And here it managed to boot into a working LWP (after crashing hard enough to cause a sudden reboot ...):
http://pastebin.com/YJkhVR8s

**Comment by markfguerra** [comment]
My G1 also has issues with GLWallpaperService, although mine were a little different. I was running the GLWallpaperTest project included in this codebase. I can see the green glClearColor, but the rotating cube is nowhere to be found. 

Also, it seems to fail every so often, on it's own, showing a black screen. then it restarts the wallpaper and the regular green color background back. I haven't seen any outright crashes but if I do I will post the logcat if I catch it misbehaving or showing the black screen again.

@mblaster What wallpaper are you testing with? 

To be honest my G1 was never so great at running Live Wallpapers of any type, let alone with OpenGL on top. Officially the device never got updated to 2.1 Eclair, so an unmodded G1 couldn't run live wallpapers in the first place.

Setup:
Android Dev Phone 1 running CyanogenMod-6.0.0-DS
Freshly wiped

**Comment by markfguerra** [comment]
I don't think anyone's going to try to fix these issues. No one has stepped up, there doesn't seem to be much interest. The device is old so the impact is low, so I'm just closing this issue.
